server:
  port: 9091

spring.application.name: spring-client-server

auth.server:
  clientId: ${AS_CLIENT_ID}
  clientSecret: ${AS_CLIENT_SECRET}
  tokenUri: ${AS_TOKEN_URI}

resource.server:
  baseUrl: ${RS_BASE_URL}
